name: .NET Test

on:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Prepare
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-restore --no-build --verbosity normal
